config/routes.rb
SambaFm::Application.routes.draw do
  devise_for :users

  resources :song_relationships, only: [:create, :destroy]
  resources :blog_followings, only: [:create, :destroy]
  resources :playlists
  resources :blogs, only: [:index, :show]
  resources :users do
    member do
      get :library
      get :stream
      get :playlists
      get :blogs
    end
  end

  root :to => 'songs#index'

end

app/views/shared/_follow.html.erb
<div class="follow_form blog_follow">
  <%= form_for current_user.blog_followings.build(blog_id: blog.id),
    remote: true do |f| %>
    <div><%= f.hidden_field :blog_id, class: "follow_input_field" %></div>
    <div class="actions"><%= f.submit "Follow" %></div>
  <% end %>
</div>

app/views/shared/_follow_form.html.erb
<div class="bfollow_<%=blog.id%> blog_follow">
<% if current_user.follows_blog?(blog) %>
  <%= render partial: 'shared/unfollow', locals: { blog: blog } %>
<% else %>
  <%= render partial: 'shared/follow', locals: { blog: blog }%>
<% end %>
</div>

app/views/shared/_header.html.erb
<tr>
  <th>Like</th>
  <th>Title</th>
  <th>Artist</th>
  <th>Blog</th>
  <th> PLAY ME!!!!!</th>
  <th>Add To Playlists</th>
</tr>

app/views/shared/_like.html.erb
<%= form_for current_user.song_relationships.build(liked_song_id: song.id),
  remote: true do |f| %>
  <div><%= f.hidden_field :liked_song_id %></div>
  <div class="actions "><%= f.submit "Like",
    :type => :image, :src => "/assets/like.png", :class =>"like_button" %></div>
<% end %>

app/views/shared/_like_form.html.erb
<% if current_user.likes_song?(song) %>
  <% @locals = { song: song } %>
  <%= render partial: 'shared/unlike', locals: { song: song } %>
<% else %>
  <%= render partial: 'shared/like', locals: { song: song }%>
<% end %>

app/views/shared/_music-player.html.erb
<div id="jquery_jplayer_1" class="jp-jplayer music_player"></div>
<div id="jp_container_1" class="jp-audio music_player">
  <div class="jp-type-single">
    <div class="jp-gui jp-interface">
      <ul class="jp-controls">
        <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
        <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
        <li><a href="javascript:;" class="jp-stop" tabindex="1">stop</a></li>
        <li><a href="javascript:;" class="jp-mute" tabindex="1" title="mute">mute</a></li>
        <li><a href="javascript:;" class="jp-unmute" tabindex="1" title="unmute">unmute</a></li>
        <li><a href="javascript:;" class="jp-volume-max" tabindex="1" title="max volume">max volume</a></li>
      </ul>
      <div class="jp-progress">
        <div class="jp-seek-bar">
          <div class="jp-play-bar"></div>
        </div>
      </div>
      <div class="jp-volume-bar">
        <div class="jp-volume-bar-value"></div>
      </div>
      <div class="jp-time-holder">
        <div class="jp-current-time"></div>
        <div class="jp-duration"></div>
      </div>
    </div>
    <div class="jp-volume-bar">
      <div class="jp-volume-bar-value"></div>
    </div>
    <div class="jp-time-holder">
      <div class="jp-current-time"></div>
      <div class="jp-duration"></div>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="leftnav">
  <ul class="nav-main pull-right">
    <% if user_signed_in? %>
      <li><%= link_to "Discovery", root_path, id: "logo", class: "nav home-nav"%></li>
      <li class="all-blogs"><%= link_to "Blogs", blogs_path, class: "sub-nav blogs-nav"%></li>
      <li><%= link_to "MyZone", library_user_path(current_user), id: "library_link", class: "nav library-nav"%></li>
      <li><%= link_to "MyStream", stream_user_path(current_user), id: "stream_link", class: "sub-nav stream-nav"%></li>
      <li class="blogs">

      <span class="arrow up" onclick="toggle_blogs()"></span>
      <%= link_to "MyBlogs", blogs_user_path(current_user), class: "sub-nav blogs_list"%>

        </li>
      <div class="my_blogs">
      <%= render partial: 'blogs/list', locals: { blogs: current_user.followed_blogs }%> </div>
      <li class="playlists">
        <%= link_to "MyPlaylists",  playlists_user_path(current_user), id: "playlists_link", class: "sub-nav playlists-nav"%>
        <span class="arrow up" onclick="toggle_playlists()"></span>
      </li>
      <div id="my_playlists" class="all_lists">
        <%= render current_user.playlists %>
      </div>
      <li id="create_playlist">
      <%= render 'playlists/new_playlist_form' %>
      </li>
    <% end %>
  </ul>
</div>

<script>
  function toggle_blogs(){
    $(".my_blogs").slideToggle("slow");
  }
  function toggle_playlists(){
    $(".all_lists").slideToggle("slow");
  }
</script>

app/views/shared/_unfollow.html.erb
<%= form_for current_user.blog_followings.find_by_blog_id(blog.id),
  html: { method: :delete }, remote: true do |f| %>
    <div class="actions"><%= f.submit "Unfollow" %></div>
<% end %>

app/views/shared/_unlike.html.erb
<%= form_for current_user.song_relationships.find_by_liked_song_id(song.id),
  html: { method: :delete }, remote: true do |f| %>
  <div class="actions"><%= f.submit "Unlike",
    :type => :image, :src => "/assets/unlike.png", :class => "unlike_button"%></div>
<% end %>