config/routes.rb
SambaFm::Application.routes.draw do
  devise_for :users

  resources :song_relationships, only: [:create, :destroy]
  resources :blog_followings, only: [:create, :destroy]
  resources :playlists
  resources :blogs, only: [:index, :show]
  resources :users do
    member do
      get :library
      get :stream
      get :playlists
      get :blogs
    end
  end

  root :to => 'songs#index'

end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :title, :artist, :length, :id, :songid, :stream_url, :blog, :source

  has_many :song_relationships, foreign_key: "liked_song_id", dependent: :destroy
  has_many :likers, through: :song_relationships
  has_many :playlist_items, dependent: :destroy

  belongs_to :blog
  validates :title, :presence => true, :uniqueness => { :case_sensitive => false }
  validates :artist, presence: true
  validates :blog, presence: true
end
# == Schema Information
#
# Table name: songs
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  artist      :string(255)
#  source      :string(255)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#  songid      :integer
#  description :string(255)
#  stream_url  :string(255)
#  blog_id     :integer
#

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter :authenticate_user!

  def splash

  end

  def index
    @songs = Song.find(:all, :order => "created_at DESC")

    respond_to do |format|
      format.js { render layout: false }
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end

  def show
    @song = Song.find(params[:id])
  end

end

app/views/songs/_song.html.erb
<li class="song_row" id="<%= song.id %>">
<div class="song_container <%= if song.id.even?
                                 "even-song" else
                                 "odd-song" end%> ">
  <div class="play_like">
    <span>
      <a class="play_button song_play not-playing"></a>
      <p id="link_url" type="hidden"><%= song.stream_url %></p>
    </span>
    <a class="like_form song_like"/>
      <%= render partial: 'shared/like_form', locals: { song: song } %>
    </a>
  </div>
  <div class="title_artist">
    <div class="song_title">
      <%= song.title %>
    </div>
    <div class="song_artist">
      by   <%= song.artist %>
    </div>
  </div>
  <div class="song_blog">
    <div class="blog_name blink_<%=song.blog.id%>">
      <%= link_to song.blog.name, blog_path(song.blog) %>
    </div>
  </div>
</div>
</li>

app/views/songs/index.html.erb
<ul class="song_table">
  <%= render @songs %>
</ul>

app/views/songs/index.js.erb
$(".content").html("<ul class='song_table'><%= escape_javascript(render @songs) %></ul>");
$(".play_button").click(init_player);

app/views/songs/show.html.erb
<%= @song.title %><br />
<%= @song.artist %>
<%= render partial: 'shared/like_form', locals: {song: @song } %>

app/views/songs/splash.html.erb
<h1>Splash</h1>