config/routes.rb
SambaFm::Application.routes.draw do
  devise_for :users

  resources :song_relationships, only: [:create, :destroy]
  resources :blog_followings, only: [:create, :destroy]
  resources :playlists
  resources :blogs, only: [:index, :show]
  resources :users do
    member do
      get :library
      get :stream
      get :playlists
      get :blogs
    end
  end

  root :to => 'songs#index'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  attr_accessible :name
  validates :user_id, presence: true
  validates :name, presence: true

  belongs_to :user
  has_many :playlist_items, order: '"playlist_items"."index" ASC',
    dependent: :destroy
  has_many :songs, through: :playlist_items
end
# == Schema Information
#
# Table name: playlists
#
#  id         :integer         not null, primary key
#  user_id    :integer
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  name       :string(255)
#

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def show
    @playlist = Playlist.find(params[:id])
    @songs = @playlist.playlist_items.collect { |item| item.song }
  end

  def create
    @playlist = current_user.create_playlist! params[:playlist][:name]

    respond_to do |format|
      format.html { redirect_to @playlist }
      format.js
    end
  end

end

app/views/playlists/_new_playlist_form.html.erb
<a class="sub-nav playlist-sub-nav playlist_new" id="playlist_create_link" href="#">Create Playlist</a>
<%= form_for current_user.playlists.build, remote: true do |f| %>
  <%= f.text_field :name, style: 'width: 100px;' %>
<% end %>

app/views/playlists/_playlist.html.erb
<li><%= link_to playlist.name, playlist_path(playlist), class: "sub-nav playlist-sub-nav user_playlist" %></li>

app/views/playlists/create.js.erb
$("#my_playlists").html("<%= escape_javascript render current_user.playlists%>");
$("#playlist_name").attr('value', '');

app/views/playlists/show.html.erb
<ul class="song_table">
  <%= render @songs %>
</ul>